import { Event } from '../types'

export const seedEvents: Event[] = [
  {
    id: 'seed-1',
    title: 'Introduction au Machine Learning',
    description: 'Un workshop pratique pour découvrir les fondamentaux du Machine Learning avec Python et scikit-learn. Aucun prérequis nécessaire.',
    category: 'Workshop',
    startDateTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
    locationName: 'Salle Info 103',
    locationAddress: 'Bâtiment A, 1er étage',
    organizerName: 'Club IA',
    capacity: 30,
    registeredCount: 12,
    tags: ['IA', 'Python', 'débutant'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-2',
    title: 'Hackathon Développement Web',
    description: '48 heures pour créer une application web innovante. Équipes de 3 à 4 personnes. Prix à gagner pour les meilleurs projets.',
    category: 'Club',
    startDateTime: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000).toISOString(),
    locationName: 'Espace Innovation',
    locationAddress: 'Bibliothèque Universitaire',
    organizerName: 'Club Dev',
    capacity: 60,
    registeredCount: 45,
    tags: ['web', 'competition', 'équipe'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-3',
    title: 'Conférence : Carrières dans la Data Science',
    description: 'Rencontre avec des professionnels du secteur pour discuter des parcours et débouchés en data science et big data.',
    category: 'Talk',
    startDateTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    locationName: 'Amphi 200',
    locationAddress: 'Bâtiment Administration',
    organizerName: 'Département Informatique',
    capacity: 150,
    registeredCount: 89,
    tags: ['carrière', 'data', 'conférence'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-4',
    title: 'Atelier CV et Lettre de Motivation',
    description: 'Atelier pratique pour améliorer votre CV et lettre de motivation avec les conseils de recruteurs.',
    category: 'Workshop',
    startDateTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    locationName: 'Salle 204',
    locationAddress: 'Bâtiment B',
    organizerName: 'Service Carrières',
    capacity: 25,
    registeredCount: 25,
    tags: ['carrière', 'CV', 'recrutement'],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-5',
    title: 'Examen de rattrapage - Algorithmique',
    description: 'Examen de rattrapage pour le module Algorithmique et Structures de Données.',
    category: 'Exam',
    startDateTime: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    locationName: 'Salles 101-105',
    organizerName: 'Département Informatique',
    capacity: 200,
    registeredCount: 0,
    tags: ['examen', 'algo', 'rattrapage'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-6',
    title: 'Sortie Culturelle : Visite de la Ville',
    description: 'Visite guidée de la médina organisée par le club culturel. Transport et repas inclus.',
    category: 'Other',
    startDateTime: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
    locationName: 'Devant l\'Université',
    organizerName: 'Club Culturel',
    capacity: 40,
    registeredCount: 28,
    tags: ['culture', 'sortie', 'visite'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-7',
    title: 'Workshop React Native',
    description: 'Apprenez à développer des applications mobiles cross-platform avec React Native et Expo.',
    category: 'Workshop',
    startDateTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
    locationName: 'Lab Info 2',
    locationAddress: 'Bâtiment C',
    organizerName: 'Club Dev Mobile',
    capacity: 20,
    registeredCount: 20,
    tags: ['mobile', 'react-native', 'expo'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-8',
    title: 'Conférence : Cybersécurité au Quotidien',
    description: 'Sensibilisation aux bonnes pratiques de cybersécurité pour les étudiants.',
    category: 'Talk',
    startDateTime: new Date(Date.now() + 17 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 17 * 24 * 60 * 60 * 1000 + 1.5 * 60 * 60 * 1000).toISOString(),
    locationName: 'Amphi 100',
    organizerName: 'Club Cyber',
    capacity: 100,
    registeredCount: 34,
    tags: ['cyber', 'sécurité', 'sensibilisation'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-9',
    title: 'Tournoi de Football Inter-Clubs',
    description: 'Tournoi annuel de football entre les clubs de l\'université. Inscriptions par équipe de 7 joueurs.',
    category: 'Club',
    startDateTime: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    locationName: 'Stade Universitaire',
    organizerName: 'Club Sportif',
    capacity: 8,
    registeredCount: 7,
    tags: ['sport', 'football', 'tournoi'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-10',
    title: 'Séance de Yoga & Méditation',
    description: 'Séance de relaxation et méditation pour décompresser entre les examens.',
    category: 'Other',
    startDateTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 1 * 60 * 60 * 1000).toISOString(),
    locationName: 'Salle Polyvalente',
    locationAddress: 'Bâtiment Sportif',
    organizerName: 'Club Bien-être',
    capacity: 15,
    registeredCount: 10,
    tags: ['bien-être', 'yoga', 'relaxation'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-11',
    title: 'Conférence : Entrepreneuriat Digital',
    description: 'Retour d\'expérience d\'entrepreneurs locaux qui ont lancé leur startup tech.',
    category: 'Talk',
    startDateTime: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    locationName: 'Amphi 300',
    organizerName: 'Incubateur Universitaire',
    capacity: 120,
    registeredCount: 55,
    tags: ['entrepreneuriat', 'startup', 'digital'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seed-12',
    title: 'Atelier : Introduction à Git & GitHub',
    description: 'Atelier pratique pour maîtriser les bases du versioning avec Git et GitHub.',
    category: 'Workshop',
    startDateTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    locationName: 'Salle Info 105',
    organizerName: 'Club Dev',
    capacity: 25,
    registeredCount: 23,
    tags: ['git', 'github', 'débutant'],
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
